[build]
  command = "npm run build"

[deploy]
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  variables = { NODE_ENV = "production" }

[services.web]
  build.command = "npm run build"
  start.command = "npm run deploy && npm start"
  healthcheck.path = "/api/health"
  healthcheck.timeout = 300
  
[services.database]
  plugin = "postgresql"
  plan = "hobby"