[build]
  command = "npm install && npx prisma generate && npx prisma db push && npm run seed && npm run build"

[deploy]
  startCommand = "npm start"

[environments.production]
  variables = { NODE_ENV = "production" }