[build]
  command = "npm install && npm run build"

[deploy]
  healthcheckPath = "/api/health"
  healthcheckTimeout = 600
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5

[environments.production]
  variables = { NODE_ENV = "production" }